{
  imports = [
    ./alacritty.nix
    ./dunst.nix
    ./eww.nix
    ./fonts.nix
    ./git.nix
    ./gtk.nix
    ./hyprland.nix
    ./nixsearch.nix
    ./nushell.nix
    ./osd.nix
    ./programs.nix
    ./qt.nix
    ./rofi.nix
    ./screenshot.nix
    ./starship.nix
    ./syncthing.nix
  ];
}